"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useState } from "react";
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [menuOpen, setMenuOpen] = useState(false);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Fixed navbar */}
        <nav className="fixed inset-x-0 top-0 z-50 h-16 bg-white shadow-md dark:bg-neutral-800">
          <div className="mx-auto h-full max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="flex h-full items-center justify-between">
              <Link
                href="/"
                className="flex flex-row items-center gap-3 text-xl font-semibold transition dark:text-neutral-200 dark:hover:text-white"
              >
                <Image alt="" src="/app-icon.png" width={44} height={44} />
                LookForward
              </Link>
              <button
                onClick={() => setMenuOpen(!menuOpen)}
                aria-expanded={menuOpen}
                aria-controls="navbarItems"
                className={`relative transform rounded-full p-2 transition-colors sm:hidden dark:text-neutral-200 dark:hover:text-white`}
              >
                <span className="relative block h-6 w-6">
                  <span
                    className={`absolute top-[6px] left-1/2 block h-0.5 w-4 origin-center -translate-x-1/2 rounded-sm bg-current transition duration-150 ease-out ${
                      menuOpen ? "translate-y-[5px] rotate-45" : ""
                    }`}
                  />
                  <span
                    className={`absolute top-[11px] left-1/2 block h-0.5 w-4 origin-center -translate-x-1/2 rounded-sm bg-current transition duration-150 ease-out ${
                      menuOpen ? "opacity-0" : ""
                    }`}
                  />
                  <span
                    className={`absolute top-[16px] left-1/2 block h-0.5 w-4 origin-center -translate-x-1/2 rounded-sm bg-current transition duration-150 ease-out ${
                      menuOpen ? "-translate-y-[5px] -rotate-45" : ""
                    }`}
                  />
                </span>
              </button>
              <div
                id="navbarItems"
                className={`${menuOpen ? "block" : "hidden"} absolute inset-x-0 top-full space-y-2 bg-white px-4 py-2 shadow-md sm:static sm:flex sm:space-y-0 sm:space-x-4 sm:bg-transparent sm:px-0 sm:py-0 sm:shadow-none dark:bg-neutral-800`}
              >
                <Link
                  href="https://ko-fi.com/cfoster"
                  className="rounded-md px-3 py-2 text-sm font-medium text-neutral-800 transition hover:text-indigo-600 dark:text-neutral-200 dark:hover:text-white"
                >
                  Buy Me a Coffee
                </Link>
                <Link
                  href="/privacy"
                  className="rounded-md px-3 py-2 text-sm font-medium text-neutral-800 transition hover:text-indigo-600 dark:text-neutral-200 dark:hover:text-white"
                >
                  Privacy Policy
                </Link>
              </div>
            </div>
          </div>
        </nav>
        {/* Page content offset for navbar */}
        <main className="pt-16 dark:bg-neutral-900">{children}</main>
      </body>
    </html>
  );
}
